language: php

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=2.2.8 DB=mysql
  - CAKE_VERSION=master DB=mysql
  - CAKE_VERSION=2.4 DB=mysql

services: elasticsearch

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../bounce app/Plugin/Bounce
  - chmod -R 777 ../cakephp/app/tmp
  - set +H
  - echo "

    CakePlugin::loadAll(array('Bounce' => array('bootstrap' => true)));" >> ../cakephp/app/Config/bootstrap.php
  - echo "<?php class DATABASE_CONFIG {

        public $default = array(
            'datasource' => 'Database/Mysql',
            'persistent' => false,
            'host' => '127.0.0.1',
            'login' => 'root',
            'password' => '',
            'database' => 'myapp',
            'prefix' => ''
        );

        public $test = array(
            'datasource' => 'Database/Mysql',
            'persistent' => false,
            'host' => '127.0.0.1',
            'login' => 'root',
            'password' => '',
            'database' => 'myapp_test',
            'prefix' => ''
        );
    }" >> ../cakephp/app/Config/database.php
  - mysql -e 'create database myapp_test;'
  - mysql -e 'use myapp_test; CREATE TABLE IF NOT EXISTS `model_classes` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `title` text,
      `track` int(11) DEFAULT NULL,
      `length` int(11) DEFAULT NULL,
      `created` datetime DEFAULT NULL,
      `modified` datetime DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB  DEFAULT CHARSET=latin1;'
  - cd app/Plugin/Bounce
  - composer self-update
  - composer install --prefer-source --dev
  - cd ../../Console

script:
  - mkdir -p build/logs
  - ./cake test Bounce AllBounce --stderr --configuration ../Plugin/Bounce/Test/phpunit.xml

after_script:
  - php ../Plugin/Bounce/vendor/bin/coveralls -v
